### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by twitchyliquid64** [AmandaCameron/golang-pam-auth#1]
Hi :D

First off, awesome stuff!

Would it be possible for you to add/grant a license to your project? Preferably MIT or similar?

I am looking into building my own golang-PAM module, something dank, but it will necessarily be derived from your version.

Thanks!
-twitch

**Comment by AmandaCameron** [comment]
This was / is very much a silly experiment with pam, as it was the first thing I thought of that loads random .so files for a plugin system. I'd prefer if you didn't use code directly from this, as it may have unseen security / stability issues, and I have no interest in fixing / maintaining it.

**Comment by twitchyliquid64** [comment]
I fully understand the limitations of experimental code and accept your disclaimers. My concern arises from the fact that, without a license of some form, all derivative works will remain affected by copyright (which is implied by default when no license exists). Moreover, without a license or disclaimer you have implied warranty.

Whilst you have no interest in maintaining it (which is totally fair), others have taken your work and productionized it, most notably https://github.com/zro/pam who has written it into an API and fixed a number of Cgo things.

While a credit section exists, the copyright remains with you (even though zro's repo is licensed under MIT - this would cause cascading licensing issues for users of his license).

Please consider a license section for all code you publish - it's one copy paste for a whole lot of peace of mind.
